#!/usr/bin/env bash
# Automate Nginx installation

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo 'Hello World' > /var/www/html/index.html
