#!/usr/bin/env bash
# Install nginx web server and then
# redirect /redirect_me $request_uri

sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World' | sudo tee /var/www/html/index.html
sudo sed -i '53 a \\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;}' /etc/nginx/sites-available/default
sudo service nginx start

