#!/usr/bin/env bash
# Install nginx web server and then
# redirect /redirect_me $request_uri

sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo -e 'Hello World' | sudo tee /var/www/html/index.html
#sudo sed -i '42 a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i "53 a \\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?=QH2-TGUlwu4\\\npermanent;\n\t}" /etc/nginx/sites-available/default
sudo service nginx start

