#!/usr/bin/env bash
# Nginx installation and configuration
sudo apt update
sudo apt -y install nginx
sudo ufw allow "Nginx HTTP"
sudo sed -i '2, $ d' /var/www/html/index.nginx-debian.html
sudo sed -i '$ a <h1>Hello World!</h1>' /var/www/html/index.nginx-debian.html
sudo sed -i "53 a \\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\\\npermanent;\n\t}" /etc/nginx/sites-available/default
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "56 a \\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo sed -i "16 a \\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
