#!/usr/bin/env bash
# Install and configure HAproxy server
sudo apt update
sudo apt install -y haproxy
sudo sed -i "$ a \\\nfrontend front_end\n\tbind *:80\n\toption forwardfor\n\tdefault_backend web_servers" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a \\\nbackend web_servers\n\tbalance roundrobin\n\tserver web1 35.175.133.237:80 check\n\tserver web2 44.200.171.3:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
